"""Marks date adjustments

Revision ID: 014122c815ad
Revises: 50f7021bd88e
Create Date: 2026-01-28 01:53:17.715132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014122c815ad'
down_revision: Union[str, Sequence[str], None] = '50f7021bd88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('mark_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'mark_date')
    # ### end Alembic commands ###
