"""Marks adjustments

Revision ID: 50f7021bd88e
Revises: 290db8a7b9ab
Create Date: 2026-01-28 01:45:57.756950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f7021bd88e'
down_revision: Union[str, Sequence[str], None] = '290db8a7b9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('quarter', sa.Integer(), server_default='0', nullable=False))
    op.add_column('marks', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'notes')
    op.drop_column('marks', 'quarter')
    # ### end Alembic commands ###
