"""Relations 3

Revision ID: 536a5bf474dd
Revises: 89a85edfc25a
Create Date: 2026-01-25 00:05:27.578446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536a5bf474dd'
down_revision: Union[str, Sequence[str], None] = '89a85edfc25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pupils', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pupils', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pupils', type_='foreignkey')
    op.drop_column('pupils', 'user_id')
    # ### end Alembic commands ###
