"""Relations 2

Revision ID: 89a85edfc25a
Revises: fa5f13271aa6
Create Date: 2026-01-25 00:02:08.916094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a85edfc25a'
down_revision: Union[str, Sequence[str], None] = 'fa5f13271aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('pupil_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'marks', 'pupils', ['pupil_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_column('marks', 'pupil_id')
    # ### end Alembic commands ###
