"""User->Pupil

Revision ID: a65a744848cf
Revises: 92211ec9a878
Create Date: 2026-01-24 23:52:28.637599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65a744848cf'
down_revision: Union[str, Sequence[str], None] = '92211ec9a878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pupils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('marks', sa.Column('pupil_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('marks_user_id_fkey'), 'marks', type_='foreignkey')
    op.create_foreign_key(None, 'marks', 'pupils', ['pupil_id'], ['id'], ondelete='CASCADE')
    op.drop_column('marks', 'user_id')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'year')
    op.drop_column('users', 'school_id')
    op.drop_column('users', 'name')
    op.drop_column('users', 'form')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('form', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.add_column('marks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.create_foreign_key(op.f('marks_user_id_fkey'), 'marks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('marks', 'pupil_id')
    op.drop_table('pupils')
    # ### end Alembic commands ###
