"""Relations

Revision ID: fa5f13271aa6
Revises: a65a744848cf
Create Date: 2026-01-25 00:01:09.143780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5f13271aa6'
down_revision: Union[str, Sequence[str], None] = 'a65a744848cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('marks_pupil_id_fkey'), 'marks', type_='foreignkey')
    op.drop_column('marks', 'pupil_id')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('marks', sa.Column('pupil_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('marks_pupil_id_fkey'), 'marks', 'pupils', ['pupil_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
